#' Download ILDIS htnl file, with legume species information
#' @param species Latin binomial name for legume species of interest
#' @param hdir Directory to store the downloaded html file
#' @return NULL
#' @export
download_ILDIS <- function(species, hdir = "ILDIS_html"){
  spec <- strsplit(species, " ")[[1]]
  spec_url <- sprintf("http://www.ildis.org/LegumeWeb?version~10.01&LegumeWeb&genus~%s&species~%s",
                      spec[1], spec[2])
  html_file <- paste0(hdir, paste(spec, collapse = "_"), ".html")
  download.file(spec_url, html_file, method = "curl")  
}

#' Extract geographical records data from ILDIS species page html
#' @param html_file The path of the html file to process
#' @details The name of the species is extracted from the filename, as generated by \code{\link{download_ILDIS}}.
#' @export
extract_ILDIS <- function(html_file) {
  spec_html <- readLines(html_file)
  spec_name <- sub("_", " ", basename(html_file))
  geo_recs <- grep("Geographical records", spec_html, fixed = TRUE) + 1
  clean_recs <- gsub("<sup>.*?</sup>", "", spec_html[geo_recs]) ## remove footnotes
  clean_recs <- gsub("<p>", "\n", clean_recs, fixed = TRUE) ## remove paragraph breaks
  clean_recs <- gsub("*", "", clean_recs, fixed = TRUE) ## remove asterisks
  clean_recs <- gsub("<.*?>", "", clean_recs) ## remove html tags
  clean_recs <- gsub("&.*?;", "", clean_recs) ## remove special html characters
  clean_recs <- gsub("(N = native, I = introduced, U = uncertain status)\n", "", clean_recs, fixed= TRUE)
  return(c(spec_name, clean_recs))
}